# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/code_test/HDL/vivado/comparator/comparator.cache/wt [current_project]
set_property parent.project_path D:/code_test/HDL/vivado/comparator/comparator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib D:/code_test/HDL/vivado/comparator/comparator.srcs/sources_1/new/comparator.vhd
read_xdc D:/code_test/HDL/vivado/comparator/comparator.srcs/constrs_1/imports/Downloads/ZYBO_master.xdc
set_property used_in_implementation false [get_files D:/code_test/HDL/vivado/comparator/comparator.srcs/constrs_1/imports/Downloads/ZYBO_master.xdc]

synth_design -top comparator -part xc7z010clg400-1
write_checkpoint -noxdef comparator.dcp
catch { report_utilization -file comparator_utilization_synth.rpt -pb comparator_utilization_synth.pb }
